# Your Google Sheet ID
google_sheet_id = "1YGdku7sd7yhpe1jODGcIoCceSffeDrhLOBr7W_6veAg"

[gcp_service_account]
type = "service_account"
project_id = "trade-order-sheet"
private_key_id = "1ba7d5d46c6b07d040cdc86a40437c2f6b9105de"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2bkElP3ii62/D
BluAKgFSnoj/JJPIeiAAokVEcWPoJYm/CKeGa+wZ8fvR4L/frb2aHjgmSQOzg7kv
pKNDVZ7tLNd4JnBhGV/HjWzWRz2E0kFO6xBKAPxpg8DAWySxl/N6bIsoAKxhVu/t
KFmgqP2e3PeAHnOp+WHPykBnztLQxN7K5dstRynXmAn5WvLUWRfWCEpeybAG5Lnv
JIBraCmWXGk3SvsBniBtPtLTA1zmsE+U3VgO1MpjwlKwAhRpSwbrhmbnopGm6ulm
8LYLPD5f7vnHflOtVqoC7ArplFznHzV5D9E24qR9bZH/bmdD/FPOis/x1lMbi/AJ
1raxhWTdAgMBAAECggEAFKVruARz6bRNhLvedSXL2obYqE+CbijsIEY9Ip7WmLpO
2ZDoLL1gDhulzT3rWSw3jg6neiW/Rny845h1ZbR19Q+jHxTymPqfLV1jGOkdHEAT
ZhQSVt2/s01W7i4ie/rfclaAdTmGSMnnA2cSpa0abvVBCX3oxy7TFAomudjdYQUF
P1Su2RGzjSadJaBiJFyRv+FuWDw21Ms1QB4/Ls6e9ysk/rszQjn3x8cp1tqlLoIV
p7er55ryfCVHVVngrvhubPkrtwMWuUdezIsBtI1DFovPmiDWHmXlb3WIaTmHkVFV
2r2pZSwbiSoxcuvPqD5VEu+o0R7I0hsJ3iRKsv0kwQKBgQD/CO88+9G3V8IBEcOi
7odPrPISO2rfPnP4h+RQ5BZXgJqYivljH6suH9lSMtaToavqK+zDYJpg9cu+Bd/V
sOG6sxEzEgn6gIiAK2id4mO/bMz0oGB/PlQ4uutBPKps9oOBMorH25ISZ0FfWTq4
UAtshqpa2vQcL2k+VHSAz3vJkQKBgQC3HvwH2mRo6MHDlvHsOfF2jQCa3QsdGJVo
wbuRRilXkBwrqOUcrsodWgfx1dRbVUPCtix6VfpHf2+k1J1k9/M1C/tFSvRx3FiJ
eQtqocEA3ziWiInAKkEpnX+i0dAO1hqTljtx+nKLNWsZGpzvZB26VSPOJX9UilLy
jnq4yjFgjQKBgQDlMxBejCmTTikqcN6TRS8R6em7fO61JxluWCJWmEWD6i4FvZAX
B1T+JN1YRBwXnYo077jedakITp4Gbp0VHNwgv+FLNoEFQhJqrZhdnCHs3Ujs6F0Q
veFPAp1+iZjYSEszB0s2BhymsWlM2ZIuJrG9nODoujH8SpeYzqnNQaqMIQKBgQCA
nvLHUU5Voab3in5CPjCr5D4YiEnWFf5bpjfowi8nocEnqWnDy8GK/EG4S0jtHeaK
TQrQorM4pPn1/KDQ2pepGtFSymMH1o0ZgjvSmerGggNtOFoI76T1ZfrQki5hPWFN
aKg4VoE95jdjWp4AR4HZ7xNHKG9XIhFA7XKleN9VwQKBgFwakrnZI+PfY6v4ngz0
mP2E9uxH+dpQ48Rg+fhZSGmG93l7g75yRifai/pgFFec0GNozJiDnee2r5demBpJ
/ya1NxxVbRTtkLSIaQ9DiiTr5yTI1nRXIlwrMqnCpodCBcnK6asxrg3rr91A7LZ+
3z4PnHaB6TUvL55lvK9xGO7O
-----END PRIVATE KEY-----
"""
client_email = "trade-order-sheet@trade-order-sheet.iam.gserviceaccount.com"
client_id = "108412571835622916648"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/trade-order-sheet%40trade-order-sheet.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[token]
pickle_b64 = "gASV/AMAAAAAAACMGWdvb2dsZS5vYXV0aDIuY3JlZGVudGlhbHOUjAtDcmVkZW50aWFsc5STlCmBlH2UKIwFdG9rZW6UjP55YTI5LkEwQVMzSDZOd09fZWZUaXZKSDlnU0FKdzdkWFdwM21zNWp6MkdaaF9PNzVZUnpZb2dWWjh0VUlmNmpHeXJZMVNXaW45YVRKZXVQYjREa3lJSlk5cUx1bDFwMEdXc0tyeHVTejhjREg4ZmZzcHk4UG9ReExpUnhkX1JYQTFoOVJrZjhMbGlKU29rb1ZERHBIcDhSSFV1SFUtSzF3WEkyM2pLYXYtajk4UXRqWTRROHBTVmJJVGxRSWNoeS1JQm9XNlJYVEJuU2s4LUNhQ2dZS0FaUVNBUllTRlFIR1gyTWlQSkNVX0RZOXhVQ3oyQnBFZTBneFpBMDIwN5SMBmV4cGlyeZSMCGRhdGV0aW1llIwIZGF0ZXRpbWWUk5RDCgfpCBYKABMI5zCUhZRSlIwOX3JlZnJlc2hfdG9rZW6UjGcxLy8wZ01RZk13SG9zNTQyQ2dZSUFSQUFHQkFTTndGLUw5SXJzTld5ZkE5QW5vdXd5bXk2eDQ3VUY2WFZPZ3hCdEZzZVRaOTBYMFl5TUJoVWNGTjdMclltNmc3MzVRT3NzUERyZXFnlIwJX2lkX3Rva2VulE6MB19zY29wZXOUXZSMKmh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZ21haWwuc2VuZJRhjA9fZGVmYXVsdF9zY29wZXOUTowPX2dyYW50ZWRfc2NvcGVzlF2UjCpodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2dtYWlsLnNlbmSUYYwKX3Rva2VuX3VyaZSMI2h0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VulIwKX2NsaWVudF9pZJSMSDQxNDUwNzIwNTQ0MC1tbW9hZjZhMTFnbnQ1NjducTExbDg0bzhhZjRrbGFzMC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbZSMDl9jbGllbnRfc2VjcmV0lIwjR09DU1BYLU5fNkhhU3ZYS1NnbVN6TVBxYzNxVEZLMXBHUkGUjBFfcXVvdGFfcHJvamVjdF9pZJROjAtfcmFwdF90b2tlbpROjBZfZW5hYmxlX3JlYXV0aF9yZWZyZXNolImMD190cnVzdF9ib3VuZGFyeZROjBBfdW5pdmVyc2VfZG9tYWlulIwOZ29vZ2xlYXBpcy5jb22UjA9fY3JlZF9maWxlX3BhdGiUTowZX3VzZV9ub25fYmxvY2tpbmdfcmVmcmVzaJSJjAhfYWNjb3VudJSMAJR1Yi4="